### ISSUE TITLE
Find a way of bringing configuration into the container

### ISSUE THREAD

**Issue by widhalmt** [Icinga/docker-icinga2#1]
Other projects use different ways of bringing configuration for Icinga 2 into the container.

Options already discussed:
* Mounting an external volume where you just put your configuration and have it loaded
* Using a reusable configuration and fill it with environment variables

Are there other ideas? Submitting more configuration via API might be doable but needs a basic configuration nonetheless.

**Comment by bodsch** [comment]
There are different ways to persist configurations.
It is important to understand that when building a Conatiner the software is installed with a valid configuration.
At startup, changes may be made to the configuration (e.g. constans.conf), which are no longer present when the Conatiner is restarted.
In this case it is not helpful to use a docker volume, because it is empty at the first start.
therefore the docker entrypoint must use appropriate mechanisms to copy persistent configurations over the existing build configuration.
